WebApplication2/WebApplication2/Models/CompanyModel.cs
namespace WebApplication2.Models
{
    public class CompanyModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

WebApplication2/WebApplication2/Models/UserModel.cs
namespace WebApplication2.Models
{
    public class UserModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Lastname { get; set; }
        public string Number { get; set; }
        public virtual CompanyModel Company { get; set; }
    }
}

WebApplication2/WebApplication2/Controllers/CompanyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication2.Controllers;
using WebApplication2.Entities;
using WebApplication2.Models;

namespace Ummc.Web.Controllers
{
    public class CompanyController : HomeController
    {
        public ActionResult Index()
        {
            List<CompanyModel> CompanyModels = new List<CompanyModel>();

            var entities = Repository.Companies.ToList();

            foreach (var entity in entities)
            {
                CompanyModels.Add(new CompanyModel
                {
                    Id = entity.Id,
                    Name = entity.Name
                });
            }

            return View(CompanyModels);
        }
        public ActionResult Create()
        {
            ViewBag.Companies = new SelectList(Repository.Companies, "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompanyModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Company entity = new Company(model.Name);

            Repository.Companies.Add(entity);
            Repository.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var entity = Repository.Companies.Find(id);
            var company = Repository.Companies.ToList().SingleOrDefault(x => x.Id == entity.Id);
            ViewBag.Companies = new SelectList(Repository.Companies, "Id", "Name", company.Id);
            if (entity != null)
            {

                var viewmodel = new CompanyModel
                {
                    Name = entity.Name,

                };
                return View(viewmodel);
            }
            return RedirectToAction("Index");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CompanyModel model)
        {
            var entity = Repository.Companies.Find(model.Id);
            var room = Repository.Companies.SingleOrDefault(x => x.Id == model.Id);
            if (entity != null)
            {
                entity.Update(model.Name);
                Repository.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var entity = Repository.Companies.Find(id);
            if (entity != null)
            {
                Repository.Companies.Remove(entity);
                Repository.SaveChanges();
            }
            return RedirectToAction("Index");

        }
    }
}

WebApplication2/WebApplication2/Controllers/HomeController.cs
using System.Web.Mvc;
using WebApplication2.Data;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        public ApplicationDbContext Repository { get; } = new ApplicationDbContext();
    }
}

WebApplication2/WebApplication2/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication2.Controllers;
using WebApplication2.Entities;
using WebApplication2.Models;

namespace Ummc.Web.Controllers
{
    public class UserController : HomeController
    {
        public ActionResult Index()
        {
            List<UserModel> UserModels = new List<UserModel>();

            var entities = Repository.Users.ToList();
            var companies = Repository.Companies.ToList();
            foreach (var entity in entities)
            {
                var company = companies.SingleOrDefault(x => x.Id == entity.Company.Id);
                UserModels.Add(new UserModel
                {
                    Id = entity.Id,
                    Surname = entity.Surname,
                    Name = entity.Name,
                    Lastname = entity.Lastname,
                    Number = entity.Number,
                    Company = new CompanyModel { Id = entity.Company.Id, Name = entity.Company.Name },
                });
            }

            return View(UserModels);
        }
        public ActionResult Create()
        {
            ViewBag.Companies = new SelectList(Repository.Companies, "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserModel model)
        {
            var company = Repository.Companies.SingleOrDefault(x => x.Id == model.Company.Id);

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            User entity = new User(model.Surname, model.Name, model.Lastname, model.Number, company);

            Repository.Users.Add(entity);
            Repository.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var entity = Repository.Users.Find(id);
            var company = Repository.Companies.ToList().SingleOrDefault(x => x.Id == entity.Company.Id);
            ViewBag.Companies = new SelectList(Repository.Companies, "Id", "Name", company.Id);
            if (entity != null)
            {

                var viewmodel = new UserModel
                {
                    Id = entity.Id,
                    Surname = entity.Surname,
                    Name = entity.Name,
                    Lastname = entity.Lastname,
                    Number = entity.Number,
                    Company = new CompanyModel { Id = company.Id, Name = company.Name },

                };
                return View(viewmodel);
            }
            return RedirectToAction("Index");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserModel model)
        {
            var entity = Repository.Users.Find(model.Id);
            var room = Repository.Companies.SingleOrDefault(x => x.Id == model.Company.Id);
            if (entity != null)
            {
                entity.Update(model.Surname, model.Name, model.Lastname, model.Number, room);
                Repository.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var entity = Repository.Users.Find(id);
            if (entity != null)
            {
                Repository.Users.Remove(entity);
                Repository.SaveChanges();
            }
            return RedirectToAction("Index");

        }
    }
}

WebApplication2/WebApplication2/Views/Company/Create.cshtml
@model WebApplication2.Models.CompanyModel

<div style="margin-top: 30px;">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="name">Название компании:</label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-warning">Сохранить</button>
    }
</div>

WebApplication2/WebApplication2/Views/Company/Edit.cshtml
@model WebApplication2.Models.CompanyModel
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.Id)
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="name">Имя:</label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-warning">Сохранить</button>
}

WebApplication2/WebApplication2/Views/Company/Index.cshtml
@model List<WebApplication2.Models.CompanyModel>
@{
    ViewBag.Title = "Оборудование";
}
<body>
    <div style="margin-top: 30px;">
        <div class="bootstrap-table">
            <div class="fixed-table-header" style="display: block;">
                <div id="toolbar">
                    <a href="@Url.Action("Create", "Company")" class="btn btn-success btn"><span class="glyphicon glyphicon-plus"></span>Добавить</a>
                </div>
                <table data-toggle="table"
                       id="table"
                       data-pagination="true"
                       data-search="true"
                       class="table table-hover"
                       data-toolbar="#toolbar">
                    <thead style="display: table-header-group">
                        <tr>
                            <th data-sortable="true">Название компании</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var v in Model)
                        {
                            <tr>
                                <td>@v.Name</td>
                                <td>
                                    @Html.AntiForgeryToken()
                                    <a href="@Url.Action("Edit","Company", new { id=v.Id})" class="btn btn-link" title="Редактировать"><span class="glyphicon glyphicon-pencil"></span></a>
                                </td>
                                <td>
                                    <form method="post" action="@Url.Action("Delete","Company", new { id=v.Id})">
                                        @Html.AntiForgeryToken()
                                        <button class="btn btn-link" type="submit" title="Удалить" onclick="return confirm('Точно удалить?')"><span class="glyphicon glyphicon-trash"></span></button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>

    <!-- Latest compiled and minified Locales -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/locale/bootstrap-table-zh-CN.min.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/WebApplication2/Views/User/Create.cshtml
@model WebApplication2.Models.UserModel

<div style="margin-top: 30px;">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="name">Фамилия:</label>
            @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">Имя:</label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">Отчество:</label>
            @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">Телефон:</label>
            @Html.TextBoxFor(m => m.Number, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="name">Компания:</label>
            @Html.DropDownListFor(m => m.Company.Id, ViewBag.Companies as SelectList, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-warning">Сохранить</button>
    }
</div>

WebApplication2/WebApplication2/Views/User/Edit.cshtml
@model WebApplication2.Models.UserModel
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.Id)
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="name">Фамилия:</label>
        @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Имя:</label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Отчество:</label>
        @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Телефон:</label>
        @Html.TextBoxFor(m => m.Number, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Компания:</label>
        @Html.DropDownListFor(m => m.Company.Id, ViewBag.Companies as SelectList, "---", new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-warning">Сохранить</button>
}

WebApplication2/WebApplication2/Views/User/Index.cshtml
@model List<WebApplication2.Models.UserModel>
@{
    ViewBag.Title = "Оборудование";
}
<body>
    <div style="margin-top: 30px;">
        <div class="bootstrap-table">
            <div class="fixed-table-header" style="display: block;">
                <div id="toolbar">
                    <a href="@Url.Action("Create", "User")" class="btn btn-success btn"><span class="glyphicon glyphicon-plus"></span>Добавить</a>
                </div>
                <table data-toggle="table"
               id="table"
               data-pagination="true"
               data-show-export="true"
               data-click-to-select="true"
               data-show-refresh="true"
               data-show-toggle="true"
               data-search="true"
               class="table table-hover"
               data-toolbar="#toolbar"
               data-page-list="[10, 25, 50, 100, Все]">
                    <thead style="display: table-header-group">
                        <tr>
                            <th data-sortable="true">Фамилия</th>
                            <th data-sortable="true">Имя</th>
                            <th data-sortable="true">Отчество</th>
                            <th data-sortable="true">Телефон</th>
                            <th data-sortable="true">Компания</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var v in Model)
                        {
                            <tr>
                                <td>@v.Surname</td>
                                <td>@v.Name</td>
                                <td>@v.Lastname</td>
                                <td>@v.Number</td>
                                <td>@v.Company.Name</td>
                                <td>
                                    @Html.AntiForgeryToken()
                                    <a href="@Url.Action("Edit","User", new { id=v.Id})" class="btn btn-link" title="Редактировать"><span class="glyphicon glyphicon-pencil"></span></a>
                                </td>
                                <td>
                                    <form method="post" action="@Url.Action("Delete","User", new { id=v.Id})">
                                        @Html.AntiForgeryToken()
                                        <button class="btn btn-link" type="submit" title="Удалить" onclick="return confirm('Точно удалить?')"><span class="glyphicon glyphicon-trash"></span></button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>